name: Test
on: [push]

jobs:
  build-fixtures:
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain-version:
          - swift-wasm-5.3.0-RELEASE
          - swift-wasm-5.4.0-RELEASE
          - swift-wasm-5.5.0-RELEASE
          - swift-wasm-5.6.0-RELEASE

    steps:
      - uses: actions/checkout@v2
      - name: Install SwiftWasm toolchain
        run: |
          VERSION=${{ matrix.toolchain-version }}
          TOOLCHAIN_URL="https://github.com/swiftwasm/swift/releases/download/$VERSION/$VERSION-macos_x86_64.pkg"
          wget $TOOLCHAIN_URL
          installer -target CurrentUserHomeDirectory -pkg $VERSION-macos_x86_64.pkg
          echo "SWIFT_TOOLCHAIN=$HOME/Library/Developer/Toolchains/$VERSION.xctoolchain/usr" >> $GITHUB_ENV
      - name: Setup fixtures
        run: |
          npm install
          npm run build
          make all
        working-directory: Fixtures
      - uses: actions/upload-artifact@v2
        with:
          name: test-fixtures-${{ matrix.toolchain-version }}
          path: Fixtures/build

  ubuntu-unit-tests:
    runs-on: ubuntu-latest
    needs: build-fixtures
    strategy:
      matrix:
        toolchain-version:
          - swift-wasm-5.3.0-RELEASE
          - swift-wasm-5.4.0-RELEASE
          - swift-wasm-5.5.0-RELEASE
          - swift-wasm-5.6.0-RELEASE
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures-${{ matrix.toolchain-version }}
          path: Fixtures/build
      - name: Install dependencies
        run: |
          curl -L -o wabt.tar.gz https://github.com/WebAssembly/wabt/releases/download/1.0.19/wabt-1.0.19-ubuntu.tar.gz
          tar xzvf wabt.tar.gz
          sudo cp wabt-*/bin/* /usr/local/bin
      - name: Run unit tests
        run: swift test --enable-test-discovery

  macos-unit-tests:
    runs-on: macos-latest
    needs: build-fixtures
    strategy:
      matrix:
        toolchain-version:
          - swift-wasm-5.3.0-RELEASE
          - swift-wasm-5.4.0-RELEASE
          - swift-wasm-5.5.0-RELEASE
          - swift-wasm-5.6.0-RELEASE
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures-${{ matrix.toolchain-version }}
          path: Fixtures/build
      - name: Select Xcode toolchain
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer/
      - name: Install dependencies
        run: brew install wabt
      - name: Run unit tests
        run: swift test

  integration-tests:
    runs-on: macos-12
    needs: build-fixtures
    strategy:
      fail-fast: false
      matrix:
        toolchain-version:
          - swift-wasm-5.3.0-RELEASE
          - swift-wasm-5.4.0-RELEASE
          - swift-wasm-5.5.0-RELEASE
          - swift-wasm-5.6.0-RELEASE
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures-${{ matrix.toolchain-version }}
          path: Fixtures/build
      - name: Select Xcode toolchain
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer/
      - name: Install dependencies
        run: |
          sudo pip3 install selenium
      - run: swift test
        working-directory: IntegrationTests
        env:
          PYTHON_VERSION: 3
