name: Test
on: [push]

jobs:
  build-fixtures:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SwiftWasm toolchain
        run: |
          VERSION=swift-wasm-5.3.0-RELEASE
          TOOLCHAIN_URL="https://github.com/swiftwasm/swift/releases/download/$VERSION/$VERSION-macos-x86_64.tar.gz"
          wget $TOOLCHAIN_URL
          tar xfz $VERSION-macos-x86_64.tar.gz
          echo "SWIFT_TOOLCHAIN=$PWD/$VERSION/usr" >> $GITHUB_ENV 
      - name: Setup fixtures
        run: |
          npm install
          npm run build
          make build/main.wasm
        working-directory: Fixtures
      - uses: actions/upload-artifact@v2
        with:
          name: test-fixtures
          path: Fixtures/build

  ubuntu-unit-tests:
    runs-on: ubuntu-latest
    needs: build-fixtures
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures
          path: Fixtures/build
      - name: Install dependencies
        run: |
          curl -L -o wabt.tar.gz https://github.com/WebAssembly/wabt/releases/download/1.0.19/wabt-1.0.19-ubuntu.tar.gz
          tar xzvf wabt.tar.gz
          sudo cp wabt-*/bin/* /usr/local/bin
      - name: Run unit tests
        run: swift test --enable-test-discovery

  macos-unit-tests:
    runs-on: macos-latest
    needs: build-fixtures
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures
          path: Fixtures/build
      - name: Select Xcode toolchain
        run: sudo xcode-select -s /Applications/Xcode_12.2.0.app/Contents/Developer/
      - name: Install dependencies
        run: brew install wabt
      - name: Run unit tests
        run: swift test

  integration-tests:
    runs-on: macos-latest
    needs: build-fixtures
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: test-fixtures
          path: Fixtures/build
      - name: Select Xcode toolchain
        run: sudo xcode-select -s /Applications/Xcode_12.2.0.app/Contents/Developer/
      - name: Install dependencies
        run: |
          sudo pip3 install selenium
      - run: swift run IntegrationTests
        working-directory: IntegrationTests
        env:
          PYTHON_VERSION: 3
